export {
  hasPermission,
  requestPermission,
  getUsageStats,
  getUsageStatsForChild,
  getTotalScreenTime,
  getInstalledApps,
  hasOverlayPermission,
  requestOverlayPermission,
  hasAccessibilityPermission,
  requestAccessibilityPermission,
  hasBatteryOptimizationBypass,
  requestBatteryOptimizationSettings,
  syncBlockerConfigs,
  getBlockingPermissionStatus,
  startAppBlocker,
  stopAppBlocker,
  setChildPin,
  listenPinVerified,
  unlistenPinVerified,
  getActiveChildId,
  logoutChild,
} from './src/ScreenTimeModule';

export type {
  AppUsageInfo,
  InstalledApp,
  PinVerifiedEvent,
  ActiveChildChangedEvent,
  BlockerChildConfig,
  BlockingPermissionStatus,
} from './src/ScreenTimeModule';
